// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4415.PIDRetro.subsystems;

import org.usfirst.frc4415.PIDRetro.Robot;
import org.usfirst.frc4415.PIDRetro.RobotMap;
import org.usfirst.frc4415.PIDRetro.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Telescope extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_TalonSRX telescopeMotor = RobotMap.telescopetelescopeMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new TelescopeDefault());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }
    
    public void telescopeUpHalf() {
    	telescopeMotor.set(-.882);
    }
    
    public void telescopeDownHalf() {
    	telescopeMotor.set(.74);
    }
    
    public void telescopeUp() {
    	telescopeMotor.set(-1);
    }
    
    public void telescopeDown() {
    	telescopeMotor.set(1);
    }
    
    public void telescopeUpPOV() {
    	if (Robot.oi.getDriverJoystick().getPOV() == 270) {
    		telescopeMotor.set(-1);
    	}
    }
    
    public void telescopeDownPOV() {
    	if (Robot.oi.getDriverJoystick().getPOV() == 90) {
    		telescopeMotor.set(1);
    	}
    }
    
    public void telescopeOff() {
    	telescopeMotor.set(0);
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

