// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4415.PIDRetro;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.RobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX driveTrainPIDleftFront;
    public static WPI_TalonSRX driveTrainPIDrightFront;
    public static WPI_TalonSRX driveTrainPIDleftRear;
    public static WPI_TalonSRX driveTrainPIDrightRear;
    public static RobotDrive driveTrainPIDRobotDrive4;
    public static Encoder driveTrainPIDQuadratureEncoder1;
    public static DoubleSolenoid driveTrainPIDDoubleSolenoid1;
    public static WPI_TalonSRX clawPIDwristMotor;
    public static WPI_TalonSRX clawPIDwheelMotor;
    public static Encoder clawPIDQuadratureEncoder1;
    public static DoubleSolenoid clawPIDDoubleSolenoid1;
    public static DigitalInput clawPIDLimitSwitch1;
    public static WPI_TalonSRX wedgeArmPIDwedgeArmMotor;
    public static Encoder wedgeArmPIDQuadratureEncoder1;
    public static DigitalInput wedgeArmPIDLimitSwitch1;
    public static WPI_TalonSRX climberPIDclimberMotor1;
    public static WPI_TalonSRX climberPIDclimberMotor2;
    public static Encoder climberPIDQuadratureEncoder1;
    public static WPI_TalonSRX telescopetelescopeMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainPIDleftFront = new WPI_TalonSRX(3);
        
        
        driveTrainPIDrightFront = new WPI_TalonSRX(4);
        
        
        driveTrainPIDleftRear = new WPI_TalonSRX(5);
        
        
        driveTrainPIDrightRear = new WPI_TalonSRX(6);
        
        
        driveTrainPIDRobotDrive4 = new RobotDrive(driveTrainPIDleftFront, driveTrainPIDleftRear,
              driveTrainPIDrightFront, driveTrainPIDrightRear);
        
        driveTrainPIDRobotDrive4.setSafetyEnabled(false);
        driveTrainPIDRobotDrive4.setExpiration(0.1);
        driveTrainPIDRobotDrive4.setSensitivity(0.5);
        driveTrainPIDRobotDrive4.setMaxOutput(1.0);

        driveTrainPIDQuadratureEncoder1 = new Encoder(0, 1, false, EncodingType.k4X);
        LiveWindow.addSensor("DriveTrainPID", "Quadrature Encoder 1", driveTrainPIDQuadratureEncoder1);
        driveTrainPIDQuadratureEncoder1.setDistancePerPulse(1.0);
        driveTrainPIDQuadratureEncoder1.setPIDSourceType(PIDSourceType.kRate);
        driveTrainPIDDoubleSolenoid1 = new DoubleSolenoid(0, 3, 4);
        LiveWindow.addActuator("DriveTrainPID", "Double Solenoid 1", driveTrainPIDDoubleSolenoid1);
        
        clawPIDwristMotor = new WPI_TalonSRX(7);
        
        
        clawPIDwheelMotor = new WPI_TalonSRX(8);
        
        
        clawPIDQuadratureEncoder1 = new Encoder(7, 8, false, EncodingType.k4X);
        LiveWindow.addSensor("ClawPID", "Quadrature Encoder 1", clawPIDQuadratureEncoder1);
        clawPIDQuadratureEncoder1.setDistancePerPulse(1.0);
        clawPIDQuadratureEncoder1.setPIDSourceType(PIDSourceType.kRate);
        clawPIDDoubleSolenoid1 = new DoubleSolenoid(0, 0, 1);
        LiveWindow.addActuator("ClawPID", "Double Solenoid 1", clawPIDDoubleSolenoid1);
        
        clawPIDLimitSwitch1 = new DigitalInput(6);
        LiveWindow.addSensor("ClawPID", "Limit Switch 1", clawPIDLimitSwitch1);
        
        wedgeArmPIDwedgeArmMotor = new WPI_TalonSRX(2);
        
        
        wedgeArmPIDQuadratureEncoder1 = new Encoder(2, 3, false, EncodingType.k4X);
        LiveWindow.addSensor("WedgeArmPID", "Quadrature Encoder 1", wedgeArmPIDQuadratureEncoder1);
        wedgeArmPIDQuadratureEncoder1.setDistancePerPulse(1.0);
        wedgeArmPIDQuadratureEncoder1.setPIDSourceType(PIDSourceType.kRate);
        wedgeArmPIDLimitSwitch1 = new DigitalInput(9);
        LiveWindow.addSensor("WedgeArmPID", "Limit Switch 1", wedgeArmPIDLimitSwitch1);
        
        climberPIDclimberMotor1 = new WPI_TalonSRX(0);
        
        
        climberPIDclimberMotor2 = new WPI_TalonSRX(1);
        
        
        climberPIDQuadratureEncoder1 = new Encoder(4, 5, false, EncodingType.k4X);
        LiveWindow.addSensor("ClimberPID", "Quadrature Encoder 1", climberPIDQuadratureEncoder1);
        climberPIDQuadratureEncoder1.setDistancePerPulse(1.0);
        climberPIDQuadratureEncoder1.setPIDSourceType(PIDSourceType.kRate);
        telescopetelescopeMotor = new WPI_TalonSRX(9);
        
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
