// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4415.PIDRetro.subsystems;

import org.usfirst.frc4415.PIDRetro.Robot;
import org.usfirst.frc4415.PIDRetro.RobotMap;
import org.usfirst.frc4415.PIDRetro.commands.*;
import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class ClawPID extends PIDSubsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_TalonSRX wristMotor = RobotMap.clawPIDwristMotor;
    private final WPI_TalonSRX wheelMotor = RobotMap.clawPIDwheelMotor;
    private final Encoder quadratureEncoder1 = RobotMap.clawPIDQuadratureEncoder1;
    private final DoubleSolenoid doubleSolenoid1 = RobotMap.clawPIDDoubleSolenoid1;
    private final DigitalInput limitSwitch1 = RobotMap.clawPIDLimitSwitch1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public boolean PIDEnabled = false;
    
    private float totalTicks = 0;
    private double totalError = 0;
    private double prevError = 0;
    public long prevTicks = 0;

    // Initialize your subsystem here
    public ClawPID() {
        
        super("ClawPID", 1.0, 0.0, 0.0);
        setAbsoluteTolerance(0.2);
        getPIDController().setContinuous(false);
        LiveWindow.addActuator("ClawPID", "PIDSubsystem Controller", getPIDController());

   

        // Use these to get going:
        // setSetpoint() -  Sets where the PID controller should move the system
        //                  to
        // enable() - Enables the PID controller.
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new ClawDefault());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }

    @Override
    protected double returnPIDInput() {
        // Return your input value for the PID loop
        // e.g. a sensor, like a potentiometer:
        // yourPot.getAverageVoltage() / kYourMaxVoltage;
 
        return quadratureEncoder1.getDistance();

    }

    @Override
    protected void usePIDOutput(double output) {
        // Use output to drive your system, like a motor
        // e.g. yourMotor.set(output);
    	
    	double changeInError = (this.getPIDController().getError() - prevError) / (System.currentTimeMillis() - prevTicks);
    	
    	totalError = totalError + this.getPIDController().getError();
    	totalError = totalError * 0.99;
    	
    	double newOutput = this.getPIDController().getError() * this.getPIDController().getP() + totalError * this.getPIDController().getI() + changeInError * this.getPIDController().getD();
    	newOutput = clamp(newOutput, -1, 1);
		
        prevError = this.getPIDController().getError();
 
        prevTicks = System.currentTimeMillis();
        
        newOutput = output;
        output = .5 * output;
        
        /*System.out.println("							Claw Voltage " + output);
        System.out.println("							Claw Encoder Value     " + quadratureEncoder1.get());
        System.out.println("							Claw PIDEnabled " + PIDEnabled);*/

        
        wristMotor.pidWrite(output);

    }
    
    public void wristUp() {
    	if (Robot.oi.getDriverJoystick().getRawAxis(2) > .4) {
    		wristMotor.set(-1);
    	}
    }
    
    public void wristDown() {
    	if (Robot.oi.getDriverJoystick().getRawAxis(3) > .4) {
    		wristMotor.set(1);
    	}
    }
    
    public void wristOff() {
    	wristMotor.set(0);
    }
    
    public void clawOpen() {
    	doubleSolenoid1.set(DoubleSolenoid.Value.kReverse);
    }
    
    public void clawClose() {
    	doubleSolenoid1.set(DoubleSolenoid.Value.kForward);
    }
    
    public void wheelIn() {
    	if (Robot.oi.getDriverJoystick().getPOV() == 0) {
    		wheelMotor.set(.8);
    	}
    }
    
    public void wheelOut() {
    	if (Robot.oi.getDriverJoystick().getPOV() == 180) {
    		wheelMotor.set(-.8);
    	}
    }
    
    public void wheelOff() {
    	wheelMotor.set(0);
    }
    
    public void resetEncoder() {
    	quadratureEncoder1.reset();
    }
    
    public boolean getLimitSwitch() {
    	return limitSwitch1.get();
    }

	private double clamp(double newOutput, int i, int j) {
		// TODO Auto-generated method stub
		return 0;
	}
}
