// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4415.RetroFinal.subsystems;

import org.usfirst.frc4415.RetroFinal.Robot;
import org.usfirst.frc4415.RetroFinal.RobotMap;
import org.usfirst.frc4415.RetroFinal.commands.*;
import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.RobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class DriveTrainPID extends PIDSubsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	
	public boolean driveTrainPIDEnabled = false;
    
    private float totalTicks = 0;
    private double totalError = 0;
    private double prevError = 0;
    public long prevTicks = 0;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_TalonSRX leftFront = RobotMap.driveTrainPIDleftFront;
    private final WPI_TalonSRX rightFront = RobotMap.driveTrainPIDrightFront;
    private final WPI_TalonSRX leftRear = RobotMap.driveTrainPIDleftRear;
    private final WPI_TalonSRX rightRear = RobotMap.driveTrainPIDrightRear;
    private final RobotDrive robotDrive4 = RobotMap.driveTrainPIDRobotDrive4;
    private final Encoder quadratureEncoder1 = RobotMap.driveTrainPIDQuadratureEncoder1;
    private final Encoder quadratureEncoder2 = RobotMap.driveTrainPIDQuadratureEncoder2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Initialize your subsystem here
    public DriveTrainPID() {
        
        super("DriveTrainPID", -0.05, 0, 0.01);
        setAbsoluteTolerance(0.2);
        getPIDController().setContinuous(false);
        LiveWindow.addActuator("DriveTrainPID", "PIDSubsystem Controller", getPIDController());


        // Use these to get going:
        // setSetpoint() -  Sets where the PID controller should move the system
        //                  to
        // enable() - Enables the PID controller.
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new DriveTrainDefault());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    @Override
    public void enable() {
      super.enable();
      
      driveTrainPIDEnabled = true;
      prevTicks = System.currentTimeMillis();
    }
    
    @Override
    public void disable() {
    	super.disable();
    	
    	driveTrainPIDEnabled = false;
    }

    @Override
    protected double returnPIDInput() {
        // Return your input value for the PID loop
        // e.g. a sensor, like a potentiometer:
        // yourPot.getAverageVoltage() / kYourMaxVoltage;

        return quadratureEncoder1.getDistance();
        
    }

    @Override
    protected void usePIDOutput(double output) {
        // Use output to drive your system, like a motor
        // e.g. yourMotor.set(output);

    	double changeInError = (this.getPIDController().getError() - prevError) / (System.currentTimeMillis() - prevTicks);
    	
    	totalError = totalError + this.getPIDController().getError();
    	totalError = totalError * 0.99;
    	
    	double newOutput = this.getPIDController().getError() * this.getPIDController().getP() + totalError * this.getPIDController().getI() + changeInError * this.getPIDController().getD();
    	newOutput = clamp(newOutput, -1, 1);
		
        prevError = this.getPIDController().getError();
 
        prevTicks = System.currentTimeMillis();
        
        newOutput = output;
        output = .5 * output;
        
        leftFront.pidWrite(-1 * output);
        rightFront.pidWrite(output);
        leftRear.pidWrite(-1 * output);
        rightRear.pidWrite(output);
        
        System.out.println("Driver Voltage " + output);
        System.out.println("Driver Encoder Value " + quadratureEncoder1.get());
        System.out.println("Driver PIDEnabled " + driveTrainPIDEnabled);
        
    }
    
    public void arcadeDrive() {
    	robotDrive4.arcadeDrive(-1 * Robot.oi.getDriverJoystick().getRawAxis(1), -1 * Robot.oi.getDriverJoystick().getRawAxis(4));
    }
    
    public void turnLeft() {
    	leftFront.set(1);
    	rightFront.set(1);
    	leftRear.set(1);
    	rightRear.set(1);
    }
    
    public void turnRight(double speed) {
    	leftFront.set(-1 * speed);
    	rightFront.set(-1 * speed);
    	leftRear.set(-1 *speed);
    	rightRear.set(-1 * speed);
    }
    
    public double getEncoder() {
    	return quadratureEncoder1.get();
    }
    
    public void resetEncoder() {
    	quadratureEncoder1.reset();
    }
    
    public void turnRightAngle(double angle, double startSlowSpeed, double speed1, double speed2, boolean resetGyro) {
    	
    	Robot.navX.reset();
    	
    	while (Robot.navX.getAngle() < (angle * startSlowSpeed)) {
    		leftFront.set(1 * speed1);
    		rightFront.set(1 * speed1);
    		leftRear.set(1 * speed1);
    		rightRear.set(1 * speed1);
    		}
    		
    		while (Robot.navX.getAngle() < angle) {
        		leftFront.set(1 * speed2);
        		rightFront.set(1 * speed2);
        		leftRear.set(1 * speed2);
        		rightRear.set(1 * speed2);
    		}
    	
    	if (resetGyro == true) {
    		Robot.navX.reset();
    	}
    	
    }
    	
    
    public void turnLeftAngle(double angle, double startSlowSpeed, double speed1, double speed2, boolean resetGyro) {  // in cm
    	
    	Robot.navX.reset();
    	
    	while (Math.abs(Robot.navX.getAngle()) < (angle * startSlowSpeed)) {
    		leftFront.set(-1 * speed1);
    		rightFront.set(-1 * speed1);
    		leftRear.set(-1 * speed1);
    		rightRear.set(-1 * speed1);
    		if (Robot.navX.getAngle() > angle * startSlowSpeed) {
    			break;
    		}
    		
    		while (Math.abs(Robot.navX.getAngle()) < angle) {
        		leftFront.set(-1 * speed2);
        		rightFront.set(-1 * speed2);
        		leftRear.set(-1 * speed2);
        		rightRear.set(-1 * speed2);
    		}
    	
    	}
    	
    	if (resetGyro == true) {
    		Robot.navX.reset();
    	}
    	
    }
    
    public void driveForwardGyroSetpoint(int setpoint) {
    	long startTime = System.currentTimeMillis();
    	while (this.getEncoder() <= setpoint && (System.currentTimeMillis() - startTime < 4000)) {
    		RobotMap.driveTrainPIDRobotDrive4.drive(.3, -Robot.navX.getAngle() * .35);
    	}
    	
    }
    
    public void driveBackwardGyroSetpoint(int setpoint) {
    	long startTime = System.currentTimeMillis();
    	while (this.getEncoder() >= setpoint && (System.currentTimeMillis() - startTime < 4000)) {
    		RobotMap.driveTrainPIDRobotDrive4.drive(-.3, -Robot.navX.getAngle() * .35);
    	}
    	
    }

	private double clamp(double newOutput, int i, int j) {
		// TODO Auto-generated method stub
		return 0;
	}
	
}
