// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4415.PIDRetro.commands;

import edu.wpi.first.wpilibj.command.TimedCommand;
import org.usfirst.frc4415.PIDRetro.Robot;

/**
 *
 */
public class StartingPositionTelescopeTimed extends TimedCommand {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR


    public StartingPositionTelescopeTimed() {
        this(0);
    }

    public StartingPositionTelescopeTimed(double timeout) {
        super(timeout);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.telescope);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {

    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	
    	Robot.telescope.telescopeDown();
    	
    }


    // Called once after isFinished returns true
    @Override
    protected void end() {
    	
    	Robot.telescope.telescopeOff();
    	
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	
    	System.out.println("aj;lsdfjsd;lfjas;dlfkjads;lkfjads;lfjasd;lfjasd;lfkjasld;fjal;sdkfjads;lfkja;sdkfjaldsfjads;lfj;ads");
    	
    }
}
