// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4415.Test4;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.RobotDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX subsystem1TalonSRX1;
    public static WPI_TalonSRX subsystem1TalonSRX2;
    public static WPI_TalonSRX subsystem1TalonSRX3;
    public static WPI_TalonSRX subsystem1TalonSRX4;
    public static RobotDrive subsystem1RobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        subsystem1TalonSRX1 = new WPI_TalonSRX(0);
        
        
        subsystem1TalonSRX2 = new WPI_TalonSRX(1);
        
        
        subsystem1TalonSRX3 = new WPI_TalonSRX(2);
        
        
        subsystem1TalonSRX4 = new WPI_TalonSRX(3);
        
        
        subsystem1RobotDrive41 = new RobotDrive(subsystem1TalonSRX1, subsystem1TalonSRX3,
              subsystem1TalonSRX2, subsystem1TalonSRX4);
        
        subsystem1RobotDrive41.setSafetyEnabled(true);
        subsystem1RobotDrive41.setExpiration(0.1);
        subsystem1RobotDrive41.setSensitivity(0.5);
        subsystem1RobotDrive41.setMaxOutput(1.0);


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
